Base Class w/ configuration
tellor-io/pytelliot pull request #56
Opened 2021-10-01 13:44 UTC by tallywiesenberg

New base class, now separate from rpc class PR #43 . This PR only creates the new class, but does not replace pydantic BaseModel in any other classes.

2021-10-01 13:57 UTC, clamdad commented
Nice.  Should we also set  `extra=False` in the base class?  I think this might prevent creating new attributes in class methods, like we saw before in the Contract class. Prob should test it though.

2021-10-01 14:51 UTC, tallywiesenberg commented
> Nice. Should we also set `extra=False` in the base class? I think this might prevent creating new attributes in class methods, like we saw before in the Contract class. Prob should test it though.

aha yes. thank you for reminding me

2021-10-04 12:43 UTC, clamdad approved these changes

2021-10-04 14:40 UTC, oraclown requested changes
Looks good, just need to pull from main

2021-10-05 14:08 UTC, oraclown approved these changes

2021-10-05 14:10 UTC, merged